/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.billmanagement;

import controller.BillDAO;
import controller.ProductDAO;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bill;
import model.User;

/**
 *
 * @author Admin
 */
public class BillManagementFrm extends javax.swing.JFrame {
    private User user;
   private Bill chosenBill;
   private ArrayList<Bill> allBills;
   private BillDAO billDAO ;
    /**
     * Creates new form BillManagementFrm
     */
    
    public BillManagementFrm(User u) {
        this.user = u;
        
        initComponents();
        billDAO = new BillDAO();
        allBills = billDAO.getAllBillsGeneralInformation();
        updateTable(allBills);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBillFrm = new javax.swing.JDialog();
        searchClientFrm = new javax.swing.JDialog();
        btnWriteBill = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearchKey = new javax.swing.JTextField();
        btnEditBill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();

        javax.swing.GroupLayout createBillFrmLayout = new javax.swing.GroupLayout(createBillFrm.getContentPane());
        createBillFrm.getContentPane().setLayout(createBillFrmLayout);
        createBillFrmLayout.setHorizontalGroup(
            createBillFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        createBillFrmLayout.setVerticalGroup(
            createBillFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout searchClientFrmLayout = new javax.swing.GroupLayout(searchClientFrm.getContentPane());
        searchClientFrm.getContentPane().setLayout(searchClientFrmLayout);
        searchClientFrmLayout.setHorizontalGroup(
            searchClientFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        searchClientFrmLayout.setVerticalGroup(
            searchClientFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnWriteBill.setText("Viết hóa đơn");
        btnWriteBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteBillActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Tìm hóa đơn ");

        btnEditBill.setText("Sửa");
        btnEditBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBillActionPerformed(evt);
            }
        });

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No .", "Mã hóa đơn", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Ngày viết", "Người viết"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBill);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnWriteBill)
                        .addGap(97, 97, 97)
                        .addComponent(btnEditBill, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditBill)
                    .addComponent(btnWriteBill))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWriteBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteBillActionPerformed
      CreateBillFrm billFrm = new CreateBillFrm(user);
      billFrm.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnWriteBillActionPerformed

    private void btnEditBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBillActionPerformed
       if(chosenBill == null){
           JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng trong bảng !");
       return;
       
       }
       Bill bill = billDAO.getById(chosenBill.getId());
       UpdateBillFrm updateBillFrm = new UpdateBillFrm(bill);
       updateBillFrm.setVisible(true);
       this.dispose();
       
       
       
       
        
        
    }//GEN-LAST:event_btnEditBillActionPerformed

    private void tblBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillMouseClicked
        int column = tblBill.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblBill.getRowHeight();
        if (row < tblBill.getRowCount() && row >= 0 && column < tblBill.getColumnCount() && column >= 0) {
            for (Bill b : this.allBills) {
                if (b.getId() == Integer.parseInt(tblBill.getValueAt(row, 1).toString())) {
                    this.chosenBill = b;
                };

            }
        }
        
        
    }//GEN-LAST:event_tblBillMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(txtSearchKey.getText()==""){
        JOptionPane.showMessageDialog(null, "Vui lòng nhập tên khách hàng !");
               return;
              
        }
        ArrayList<Bill> searchBills = billDAO.searchBillsGeneralInformationByClientName(txtSearchKey.getText());
        updateTable(searchBills);
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditBill;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnWriteBill;
    private javax.swing.JDialog createBillFrm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog searchClientFrm;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtSearchKey;
    // End of variables declaration//GEN-END:variables

private void updateTable(ArrayList<Bill> bills){
String[][] data = new String[bills.size()][7];
Bill bill = null;
for(int i = 0 ; i <bills.size();i++){
    bill = bills.get(i);
data[i][0] =i+1+"";
data[i][1] = bill.getId()+"";
data[i][2]= bill.getClient().getName();
data[i][3] =bill.getClient().getPhoneNumber()+"";
data[i][4] = bill.getClient().getAddress();
data[i][5] = bill.getWriteDate().format(DateTimeFormatter.ofPattern("d-M-y"));
data[i][6] = bill.getUser().getFullName();

} 

DefaultTableModel model = new DefaultTableModel(data,new String [] {
                "No .", "Mã hóa đơn", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Ngày viết", "Người viết"
            });
tblBill.setModel(model);





}

}
