/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.User;
import view.billmanagement.BillManagementFrm;

/**
 *
 * @author Admin
 */
public class HomeFrm extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form HomeFrm
     */
    public HomeFrm(User u) {
        this.user = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientManagement = new javax.swing.JButton();
        btnProductManagement = new javax.swing.JButton();
        btnBillManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClientManagement.setText("Quản lý khách hàng");
        btnClientManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientManagementActionPerformed(evt);
            }
        });

        btnProductManagement.setText("Quản lý sản phẩm");
        btnProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductManagementActionPerformed(evt);
            }
        });

        btnBillManagement.setText("Quản lý hóa đơn");
        btnBillManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClientManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(btnProductManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBillManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnClientManagement)
                .addGap(30, 30, 30)
                .addComponent(btnProductManagement)
                .addGap(28, 28, 28)
                .addComponent(btnBillManagement)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientManagementActionPerformed
        ClientManagementFrm clientManagementFrm = new ClientManagementFrm(user);
        clientManagementFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClientManagementActionPerformed

    private void btnProductManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductManagementActionPerformed
        ProductManagementFrm productManagementFrm = new ProductManagementFrm(user);
        productManagementFrm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnProductManagementActionPerformed

    private void btnBillManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagementActionPerformed
        BillManagementFrm billManagementFrm = new BillManagementFrm(user);
        billManagementFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBillManagementActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillManagement;
    private javax.swing.JButton btnClientManagement;
    private javax.swing.JButton btnProductManagement;
    // End of variables declaration//GEN-END:variables
}
