/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.stat;

import controller.BillDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bill;
import model.OrderLine;
import model.Statistic;
import model.User;

/**
 *
 * @author Admin
 */
public class StatDetailFrm extends javax.swing.JFrame {

    /**
     * Creates new form StatDetail
     */
    private Statistic stat;
    private User user;
    private BillDAO billDAO;
    private ArrayList<Bill> productBills;
    public StatDetailFrm(Statistic s, User u) {
        this.user = u;
        billDAO = new BillDAO();
        this.stat = s;
        initComponents();
        setLocationRelativeTo(null);

        lblProductName.setText(stat.getProductName());
        productBills = billDAO.getBillsByProductId(this.stat.getId());
        loadDataTable(productBills);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStatDetail = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ngày bắt đầu");

        jLabel2.setText("Ngày kết thúc");

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên mặt hàng");

        lblProductName.setText("jLabel4");

        tblStatDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No .", "Ngày bán", "Số lượng bán", "Giá bán", "Tổng tiền", "Mã hóa đơn", "Tên khách hàng", "Mã khách hàng", "Người bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStatDetail);

        btnBack.setText("Quay Lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnSearch)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnBack))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String startDate = txtStartDate.getText();
        String endDate = txtEndDate.getText();

        String regexDate = "^\\d{2}-\\d{2}-\\d{4}$";
        if(!Pattern.matches(regexDate, startDate)){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày bắt đầu vd : 18-12-1972");
        return;
        }
        if (!Pattern.matches(regexDate, endDate)) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày kết thúc ex : 25-10-1965");
                    return;
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d-M-y");
        System.out.println(LocalDate.parse(startDate, formatter));
        System.out.println(LocalDate.parse(endDate, formatter));

        ArrayList<Bill> searchBills = billDAO.getBillsByProductIdAndDateBetweenStartDateAndEndDate(stat.getId(), LocalDate.parse(startDate, formatter), LocalDate.parse(endDate, formatter));
        loadDataTable(searchBills);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        StatFrm statFrm = new StatFrm(user);
        statFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JTable tblStatDetail;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    void loadDataTable(ArrayList<Bill> bills) {
        String[][] data = new String[bills.size()+1][9];
        int sum = 0;
        for (int i = 0; i <= bills.size(); i++) {
           
            if (i == bills.size()) {
                data[i][0] = "Tổng tiền hàng";
                data[i][4] = sum+"";
                break;
            }
            Bill bill = bills.get(i);
            OrderLine orderLine = bill.getOrderLines().get(0);
            data[i][0] = i+1+"";
            data[i][1] = bill.getWriteDate().format(DateTimeFormatter.ofPattern("d-M-y"));
            data[i][2] = orderLine.getAmount()+"";
            data[i][3] = orderLine.getSellPrice()+"";
            data[i][4] = orderLine.getTotal()+"";
            data[i][5] = bill.getId()+"";
            data[i][6] = bill.getClient().getName();
            data[i][7] = bill.getClient().getId()+"";
            data[i][8] = bill.getUser().getFullName();
            sum += orderLine.getTotal();
        }

        DefaultTableModel model = new DefaultTableModel(data, new String [] {
                "No .", "Ngày bán", "Số lượng bán", "Giá bán", "Tổng tiền", "Mã hóa đơn", "Tên khách hàng", "Mã khách hàng", "Người bán"
            } );
        tblStatDetail.setModel(model);
    }
}
