/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.productmanagement;

import controller.ProductDAO;
import java.awt.Font;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Description;
import model.Product;
import model.User;
import view.HomeFrm;

/**
 *
 * @author Admin
 */
public class ProductManagementFrm extends javax.swing.JFrame {

    private User user;
    private ProductDAO productDAO;
    private String[][] data;
    private ArrayList<Product> allProducts;

    private Product chosenProduct;

    /**
     * Creates new form ProductManagement
     */
    public ProductManagementFrm(User u) {
        productDAO = new ProductDAO();
        this.user = u;
        initComponents();
        lblTitle.setFont(new Font("Serif", Font.PLAIN, 20));
        this.setLocationRelativeTo(null);
        this.addDialog.setLocationRelativeTo(null);
        this.editDialog.setLocationRelativeTo(null);
        allProducts = productDAO.getAllProduct();
        updateTableProduct(allProducts);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        lblAddProduct = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblAddProduct1 = new javax.swing.JLabel();
        txtCalculationUnit = new javax.swing.JTextField();
        lblAddProduct2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblAddProduct3 = new javax.swing.JLabel();
        txtStickerPrice = new javax.swing.JTextField();
        lblAddProduct4 = new javax.swing.JLabel();
        txtOrigin = new javax.swing.JTextField();
        lblAddProduct5 = new javax.swing.JLabel();
        txtSupplyCompany = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUpdateCalculationUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUpdateAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUpdateStickerPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUpdateOrigin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUpdateSupplyCompany = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAddNewProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearchKey = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        addDialog.setMinimumSize(new java.awt.Dimension(400, 400));
        addDialog.setModal(true);

        lblAddProduct.setText("Tên sản phẩm");

        lblAddProduct1.setText("Đơn vị tính");

        lblAddProduct2.setText("Số lượng");

        lblAddProduct3.setText("Giá niêm yết");

        lblAddProduct4.setText("Nguồn gốc");

        lblAddProduct5.setText("Công ty cung cấp");

        jLabel1.setText("Thêm sản phẩm");

        btnAdd.setText("Lưu");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(lblAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStickerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct1)
                    .addComponent(txtCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct2)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct3)
                    .addComponent(txtStickerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct4)
                    .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct5)
                    .addComponent(txtSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        addDialog.getAccessibleContext().setAccessibleName("addDialog");

        editDialog.setMinimumSize(new java.awt.Dimension(600, 400));
        editDialog.setModal(true);

        jLabel3.setText("Chỉnh sửa sản phẩm");

        jLabel4.setText("Tên sản phẩm");

        jLabel5.setText("Đơn vị tính");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Giá niêm yết");

        jLabel8.setText("Nguồn gốc");

        jLabel9.setText("Công ty cung cấp");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUpdateSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUpdateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUpdateCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUpdateStickerPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpdateOrigin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUpdateCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUpdateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUpdateStickerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUpdateSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddNewProduct.setText("Thêm sản phẩm");
        btnAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProductActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm sản phẩm");

        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No .", "ID sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Nguồn gốc", "Công ty sản xuất", "Tồn kho", "Giá niêm yết", "Tổng giá trị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTitle.setText("Quản lý sản phẩm");

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnAddNewProduct)
                .addGap(152, 152, 152)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnAddNewProduct))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
        addDialog.setVisible(true);
       


    }//GEN-LAST:event_btnAddNewProductActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String productName = txtProductName.getText();
        String calculationUnit = txtCalculationUnit.getText();
        String amount =txtAmount.getText();
        String stickerPrice = txtStickerPrice.getText();
        String regexNumber = "^\\d{1,}$";
        if (productName.isBlank() || productName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra tên sản phẩm");
            return;
        }
        if (calculationUnit.isBlank() || calculationUnit.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra đơn vị tính");
            return;
        }
        if (!Pattern.matches(regexNumber, amount)) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra số lượng");
            return;
        }
        if (!Pattern.matches(regexNumber, stickerPrice)) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra giá niêm yết");
            return;

        }
        Product product = new Product();
        product.setProductName(productName);
        product.setCalculationUnit(calculationUnit);
        product.setAmount(Integer.parseInt(amount));
        product.setStickerPrice(Integer.parseInt(stickerPrice));

        Description des = new Description();
        des.setOrigin(txtOrigin.getText());
        des.setSupplyCompany(txtSupplyCompany.getText());
        product.setDescription(des);

        if (productDAO.createProduct(product)) {
            JOptionPane.showMessageDialog(null, "Thêm mới sản phẩm thành công");
            allProducts.add(product);
            updateTableProduct(allProducts);;
        } else {
            chosenProduct = null;

            JOptionPane.showMessageDialog(null, "Thêm mới sản phẩm thất bại");

        }
        txtProductName.setText("");
        txtCalculationUnit.setText("");
        txtAmount.setText("");
        txtStickerPrice.setText("");
        txtOrigin.setText("");
        txtSupplyCompany.setText("");
        addDialog.dispose();
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if (txtSearchKey.getText() == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên sản phẩm !");
            return;
        }
        ArrayList<Product> searchProducts = productDAO.searchByProductName(txtSearchKey.getText());
        updateTableProduct(searchProducts);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        int column = tblProduct.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblProduct.getRowHeight();
        if (row < tblProduct.getRowCount() && row >= 0 && column < tblProduct.getColumnCount() && column >= 0) {
            for (Product c : this.allProducts) {
                if (c.getId() == Integer.parseInt(tblProduct.getValueAt(row, 1).toString())) {
                    this.chosenProduct = c;
                };

            }
        }
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (chosenProduct == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng trong bảng !");
            return;
        }
        this.txtUpdateName.setText(chosenProduct.getProductName());
        this.txtUpdateCalculationUnit.setText(chosenProduct.getCalculationUnit());
        this.txtUpdateAmount.setText(chosenProduct.getAmount() + "");
        this.txtUpdateStickerPrice.setText(chosenProduct.getStickerPrice() + "");
        this.txtUpdateOrigin.setText(chosenProduct.getDescription().getOrigin());
        this.txtUpdateSupplyCompany.setText(chosenProduct.getDescription().getSupplyCompany());
        editDialog.setVisible(true);
       


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String regexNumber = "^\\d{1,}$";
        String updateName = txtUpdateName.getText();
        String updateCalUnit = txtUpdateCalculationUnit.getText();
        String updateAmount = txtUpdateAmount.getText();
        String updateStickerPrice = txtUpdateStickerPrice.getText();

        if (updateName.isBlank() || updateName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật tên sản phẩm");
            return;

        }
        if (updateCalUnit.isBlank() || updateCalUnit.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật đơn vị tính");
            return;
        }
        if (!Pattern.matches(regexNumber, updateAmount)) {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật số lượng");
            return;

        }
        if (!Pattern.matches(regexNumber, updateStickerPrice)) {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật giá niêm yết");
            return;

        }
        Product test = new Product();
        test.setId(chosenProduct.getId());
        test.setProductName(updateName);
        test.setCalculationUnit(updateCalUnit);
        test.setAmount(Integer.parseInt(updateAmount));
        test.setStickerPrice(Integer.parseInt(updateStickerPrice));

        Description testDes = new Description();
        testDes.setId(chosenProduct.getDescription().getId());
        testDes.setOrigin(txtUpdateOrigin.getText());
        testDes.setSupplyCompany(txtUpdateSupplyCompany.getText());
        test.setDescription(testDes);

       
        if (productDAO.updateProduct(test)) {
            chosenProduct.setProductName(updateName);
            chosenProduct.setCalculationUnit(updateCalUnit);
            chosenProduct.setAmount(Integer.parseInt(updateAmount));
            chosenProduct.setStickerPrice(Integer.parseInt(updateStickerPrice));
            chosenProduct.getDescription().setOrigin(txtUpdateOrigin.getText());
            chosenProduct.getDescription().setSupplyCompany(txtUpdateSupplyCompany.getText());
            JOptionPane.showMessageDialog(null, "Cập nhật sản phẩm thành công !");
            updateTableProduct(allProducts);
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật sản phẩm thất bại !");
            return;
        }
        chosenProduct = null;
        txtUpdateName.setText("");
        txtUpdateCalculationUnit.setText("");
        txtUpdateAmount.setText("");
        txtUpdateStickerPrice.setText("");
        txtUpdateOrigin.setText("");
        txtUpdateSupplyCompany.setText("");

        editDialog.setVisible(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (chosenProduct == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng trong bảng !");
            return;

        }
        int confirm = JOptionPane.showConfirmDialog(null, "Xác nhận xóa sản phẩm : " + chosenProduct.getProductName(), "Xóa sản phẩm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (productDAO.deleteProduct(chosenProduct.getId())) {
                JOptionPane.showMessageDialog(null, "Xóa sản phẩm thành công !");
                for (int i = 0; i < allProducts.size(); i++) {
                    Product temp = allProducts.get(i);
                    if (temp.getId() == chosenProduct.getId()) {
                        allProducts.remove(i);

                    }

                }

                updateTableProduct(allProducts);
            } else {
                JOptionPane.showMessageDialog(null, "Xóa sản phẩm thất bại !");

            }
            chosenProduct = null;

        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        HomeFrm homeFrm = new HomeFrm(user);
        homeFrm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JDialog editDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblAddProduct1;
    private javax.swing.JLabel lblAddProduct2;
    private javax.swing.JLabel lblAddProduct3;
    private javax.swing.JLabel lblAddProduct4;
    private javax.swing.JLabel lblAddProduct5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCalculationUnit;
    private javax.swing.JTextField txtOrigin;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSearchKey;
    private javax.swing.JTextField txtStickerPrice;
    private javax.swing.JTextField txtSupplyCompany;
    private javax.swing.JTextField txtUpdateAmount;
    private javax.swing.JTextField txtUpdateCalculationUnit;
    private javax.swing.JTextField txtUpdateName;
    private javax.swing.JTextField txtUpdateOrigin;
    private javax.swing.JTextField txtUpdateStickerPrice;
    private javax.swing.JTextField txtUpdateSupplyCompany;
    // End of variables declaration//GEN-END:variables

    private void updateTableProduct(ArrayList<Product> products) {
        String[][] data = new String[products.size() + 1][9];
        int sum = 0;
        for (int i = 0; i <= products.size(); i++) {
            if (i == products.size()) {
                data[i][0] = "Tổng giá trị";
                data[i][tblProduct.getColumnCount() - 1] = sum+"";
                break;
            }
            Product product = products.get(i);
            data[i][0] = i + 1 + "";
            data[i][1] = product.getId() + "";
            data[i][2] = product.getProductName();
            data[i][3] = product.getCalculationUnit();
            data[i][4] = product.getDescription().getOrigin();
            data[i][5] = product.getDescription().getSupplyCompany();
            data[i][6] = product.getAmount() + "";
            data[i][7] = product.getStickerPrice() + "";
            data[i][8] = product.getAmount()*product.getStickerPrice()+"";
            sum+=(product.getAmount()*product.getStickerPrice());
        }
        DefaultTableModel tblModel = new DefaultTableModel(data, new String[]{"No .", "ID sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Nguồn gốc", "Công ty sản xuất", "Tồn kho", "Giá niêm yết", "Tổng giá trị"});
        //tblModel = new DefaultTableModel(data,)
        tblProduct.setModel(tblModel);

    }

}
