/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProductDAO;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import model.Description;
import model.Product;
import model.User;

/**
 *
 * @author Admin
 */
public class ProductManagementFrm extends javax.swing.JFrame {

    private User user;
    private ProductDAO productDAO;
    private String[][] data;
    private ArrayList<Product> allProducts;
    private ArrayList<Product> searchProducts;
    private DefaultTableModel tblModel;
    private Product chosenProduct;

    /**
     * Creates new form ProductManagement
     */
    public ProductManagementFrm(User u) {
        productDAO = new ProductDAO();
        this.user = u;
        initComponents();

        allProducts = productDAO.getAllProduct();
        updateTableProduct();
        addDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        editDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        lblAddProduct = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblAddProduct1 = new javax.swing.JLabel();
        txtCalculationUnit = new javax.swing.JTextField();
        lblAddProduct2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblAddProduct3 = new javax.swing.JLabel();
        txtStickerPrice = new javax.swing.JTextField();
        lblAddProduct4 = new javax.swing.JLabel();
        txtOrigin = new javax.swing.JTextField();
        lblAddProduct5 = new javax.swing.JLabel();
        txtSupplyCompany = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUpdateCalculationUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUpdateAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUpdateStickerPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUpdateOrigin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUpdateSupplyCompany = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnAddNewProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearchKey = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        addDialog.setMinimumSize(new java.awt.Dimension(400, 400));
        addDialog.setModal(true);

        lblAddProduct.setText("Tên sản phẩm");

        lblAddProduct1.setText("Đơn vị tính");

        lblAddProduct2.setText("Số lượng");

        lblAddProduct3.setText("Giá niêm yết");

        lblAddProduct4.setText("Nguồn gốc");

        lblAddProduct5.setText("Công ty cung cấp");

        jLabel1.setText("Thêm sản phẩm");

        btnAdd.setText("Lưu");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStickerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addDialogLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct1)
                    .addComponent(txtCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct2)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct3)
                    .addComponent(txtStickerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct4)
                    .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProduct5)
                    .addComponent(txtSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        addDialog.getAccessibleContext().setAccessibleName("addDialog");

        editDialog.setMinimumSize(new java.awt.Dimension(600, 400));
        editDialog.setModal(true);

        jLabel3.setText("Chỉnh sửa sản phẩm");

        jLabel4.setText("Tên sản phẩm");

        jLabel5.setText("Đơn vị tính");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Giá niêm yết");

        jLabel8.setText("Nguồn gốc");

        jLabel9.setText("Công ty cung cấp");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUpdateSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUpdateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDialogLayout.createSequentialGroup()
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUpdateCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUpdateStickerPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpdateOrigin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUpdateCalculationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUpdateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUpdateStickerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUpdateSupplyCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddNewProduct.setText("Thêm sản phẩm");
        btnAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProductActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm sản phẩm");

        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No .", "ID sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Số lượng", "Giá niêm yết", "Nguồn gốc", "Công ty Sản Xuất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnAddNewProduct)
                                .addGap(89, 89, 89)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewProduct)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
        addDialog.setVisible(true);
        Product product = new Product();
        product.setProductName(txtProductName.getText());
        product.setCalculationUnit(txtCalculationUnit.getText());
        product.setAmount(Integer.parseInt(txtAmount.getText()));
        product.setStickerPrice(Integer.parseInt(txtStickerPrice.getText()));

        Description des = new Description();
        des.setOrigin(txtOrigin.getText());
        des.setSupplyCompany(txtSupplyCompany.getText());
        product.setDescription(des);

        if (productDAO.createProduct(product)) {
            JOptionPane.showMessageDialog(null, "Thêm mới sản phẩm thành công");

        } else {

            JOptionPane.showMessageDialog(null, "Thêm mới sản phẩm thất bại");

        }
        HomeFrm frm = new HomeFrm(user);
        frm.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnAddNewProductActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String productName = txtProductName.getText();
        String calculationUnit = txtCalculationUnit.getText();
        String regexNumber = "^\\d{1,}$";
        if (productName.isBlank() || productName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra tên sản phẩm");
            return;
        }
        if (calculationUnit.isBlank() || calculationUnit.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra đơn vị tính");
            return;
        }
        if (!Pattern.matches(regexNumber, txtAmount.getText())) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra số lượng");
            return;
        }
        if (!Pattern.matches(regexNumber, txtStickerPrice.getText())) {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra giá niêm yết");
            return;

        }
        addDialog.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        System.out.println("In here");
        if (txtSearchKey.getText() == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên sản phẩm !");
            return;
        }
        this.searchProducts = productDAO.searchByProductName(txtSearchKey.getText());
        data = new String[searchProducts.size()][8];
        for (int i = 0; i < searchProducts.size(); i++) {
            Product product = searchProducts.get(i);
            data[i][0] = i + 1 + "";
            data[i][1] = product.getId() + "";
            data[i][2] = product.getProductName();
            data[i][3] = product.getCalculationUnit();
            data[i][4] = product.getAmount() + "";
            data[i][5] = product.getStickerPrice() + "";
            data[i][6] = product.getDescription().getOrigin();
            data[i][7] = product.getDescription().getSupplyCompany();
        }
        tblModel = new DefaultTableModel(data, new String[]{"No .", "ID sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Số lượng", "Giá niêm yết", "Nguồn gốc", "Công ty Sản Xuất"});
        //tblModel = new DefaultTableModel(data,)
        tblProduct.setModel(tblModel);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
         int column = tblProduct.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblProduct.getRowHeight();
        if (row < tblProduct.getRowCount() && row >= 0 && column < tblProduct.getColumnCount() && column >= 0) {
            for (Product c : this.allProducts) {
                if (c.getId() == Integer.parseInt(tblProduct.getValueAt(row, 1).toString())) {
                    this.chosenProduct = c;
                };

            }
        }
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (chosenProduct == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng trong bảng !");
            return;
        }
        this.txtUpdateName.setText(chosenProduct.getProductName());
        this.txtUpdateCalculationUnit.setText(chosenProduct.getCalculationUnit());
        this.txtUpdateAmount.setText(chosenProduct.getAmount() + "");
        this.txtUpdateStickerPrice.setText(chosenProduct.getStickerPrice() + "");
        this.txtUpdateOrigin.setText(chosenProduct.getDescription().getOrigin());
        this.txtUpdateSupplyCompany.setText(chosenProduct.getDescription().getSupplyCompany());
        editDialog.setVisible(true);
        chosenProduct.setProductName(txtUpdateName.getText());
        chosenProduct.setCalculationUnit(txtUpdateCalculationUnit.getText());
        chosenProduct.setAmount(Integer.parseInt(txtUpdateAmount.getText()));
        chosenProduct.setStickerPrice(Integer.parseInt(txtUpdateStickerPrice.getText()));
        chosenProduct.getDescription().setOrigin(txtUpdateOrigin.getText());
        chosenProduct.getDescription().setSupplyCompany(txtUpdateSupplyCompany.getText());
        if (productDAO.updateProduct(chosenProduct)) {
            JOptionPane.showMessageDialog(null, "Cập nhật sản phẩm thành công !");

        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật sản phẩm thất bại !");
            return;
        }
        updateTableProduct();


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String regexNumber = "^\\d{1,}$";
        String updateName = txtUpdateName.getText();
        String updateCalUnit = txtCalculationUnit.getText();
        String updateAmount = txtUpdateAmount.getText();
        String updateStickerPrice = txtUpdateStickerPrice.getText();

        if (updateName == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật tên sản phẩm");
            return;

        }
        if (updateCalUnit == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật đơn vị tính");
            return;
        }
        if (updateAmount == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật số lượng");
            return;

        }
        if (updateStickerPrice == "") {
            JOptionPane.showMessageDialog(null, "Vui lòng cập nhật giá niêm yết");
            return;

        }
        editDialog.setVisible(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (chosenProduct == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng trong bảng !");
            return;

        }
        int confirm = JOptionPane.showConfirmDialog(null, "Xác nhận xóa sản phẩm : " + chosenProduct.getProductName(), "Xóa sản phẩm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (productDAO.deleteProduct(chosenProduct.getId())) {
                JOptionPane.showMessageDialog(null, "Xóa sản phẩm thành công !");
                for (int i = 0; i < allProducts.size(); i++) {
                    Product temp = allProducts.get(i);
                    if (temp.getId() == chosenProduct.getId()) {
                        allProducts.remove(i);

                    }

                }

                    updateTableProduct();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa sản phẩm thất bại !");

            }

        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JDialog editDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblAddProduct1;
    private javax.swing.JLabel lblAddProduct2;
    private javax.swing.JLabel lblAddProduct3;
    private javax.swing.JLabel lblAddProduct4;
    private javax.swing.JLabel lblAddProduct5;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCalculationUnit;
    private javax.swing.JTextField txtOrigin;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSearchKey;
    private javax.swing.JTextField txtStickerPrice;
    private javax.swing.JTextField txtSupplyCompany;
    private javax.swing.JTextField txtUpdateAmount;
    private javax.swing.JTextField txtUpdateCalculationUnit;
    private javax.swing.JTextField txtUpdateName;
    private javax.swing.JTextField txtUpdateOrigin;
    private javax.swing.JTextField txtUpdateStickerPrice;
    private javax.swing.JTextField txtUpdateSupplyCompany;
    // End of variables declaration//GEN-END:variables

    private void updateTableProduct(){
        data = new String[allProducts.size()][8];
                for (int i = 0; i < allProducts.size(); i++) {
                    Product product = allProducts.get(i);
                    data[i][0] = i + 1 + "";
                    data[i][1] = product.getId() + "";
                    data[i][2] = product.getProductName();
                    data[i][3] = product.getCalculationUnit();
                    data[i][4] = product.getAmount() + "";
                    data[i][5] = product.getStickerPrice() + "";
                    data[i][6] = product.getDescription().getOrigin();
                    data[i][7] = product.getDescription().getSupplyCompany();
                }
                tblModel = new DefaultTableModel(data, new String[]{"No .", "ID sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Số lượng", "Giá niêm yết", "Nguồn gốc", "Công ty Sản Xuất"});
                //tblModel = new DefaultTableModel(data,)
                tblProduct.setModel(tblModel);
    
    
    
    }

}
